apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  # NOTE: Google OAuth credentials will be injected by dex-secret-injector Job
  # The placeholders below will be replaced with real values from OnePassword
  dex.config: |
    connectors:
      - type: google
        id: google
        name: Google
        config:
          issuer: https://accounts.google.com
          clientID: $dex.google.clientID  # PLACEHOLDER - will be replaced
          clientSecret: $dex.google.clientSecret  # PLACEHOLDER - will be replaced
          redirectURI: https://argocd.tail9402f.ts.net/api/dex/callback
          hostedDomains:
            - heimark.org
  url: https://argocd.tail9402f.ts.net