apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex-secret-injector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "75"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dex-secret-injector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "75"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dex-secret-injector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "75"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dex-secret-injector
subjects:
- kind: ServiceAccount
  name: dex-secret-injector
  namespace: argocd