apiVersion: batch/v1
kind: Job
metadata:
  name: dex-secret-injector
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "80"
    # This checksum will change when the source secret changes, forcing re-execution
    # ArgoCD will automatically replace this with the actual secret checksum
    checksum/secret: ${ARGOCD_GOOGLE_OAUTH_SECRET_CHECKSUM}
spec:
  template:
    spec:
      serviceAccountName: dex-secret-injector
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Wait for the OnePassword-created secret to exist
          echo "Waiting for OnePassword secret..."
          while ! kubectl -n argocd get secret argocd-google-oauth >/dev/null 2>&1; do
            sleep 2
          done

          # Read the real Google OAuth credentials
          echo "Reading Google OAuth credentials..."
          CLIENT_ID=$(kubectl -n argocd get secret argocd-google-oauth -o jsonpath='{.data.clientID}' | base64 -d)
          CLIENT_SECRET=$(kubectl -n argocd get secret argocd-google-oauth -o jsonpath='{.data.clientSecret}' | base64 -d)

          # Only proceed if we got valid credentials
          if [ -z "$CLIENT_ID" ] || [ -z "$CLIENT_SECRET" ]; then
            echo "ERROR: Failed to read Google OAuth credentials from secret"
            exit 1
          fi

          echo "Injecting Google OAuth credentials into argocd-cm..."

          # Patch the ConfigMap with real values
          kubectl -n argocd patch configmap argocd-cm --type merge -p "$(cat <<EOF
{
  "data": {
    "dex.config": "connectors:\n- type: google\n  id: google\n  name: Google\n  config:\n    issuer: https://accounts.google.com\n    clientID: \"$CLIENT_ID\"\n    clientSecret: \"$CLIENT_SECRET\"\n    redirectURI: https://argocd.tail9402f.ts.net/api/dex/callback\n    hostedDomains:\n    - heimark.org\n"
  }
}
EOF
          )"

          # Restart Dex to pick up the new config
          echo "Restarting argocd-dex-server..."
          kubectl -n argocd patch deployment argocd-dex-server -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/restartedAt\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}}}}}"

          echo "Dex secret injection completed successfully!"
      restartPolicy: Never
  backoffLimit: 4