apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: operator-oauth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  itemPath: "vaults/ArgoCDTest/items/tailscale-credentials"