apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-onepassword-crd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for OnePasswordItem CRD to be available..."
              until kubectl get crd onepassworditems.onepassword.com >/dev/null 2>&1; do
                echo "OnePasswordItem CRD not available yet, waiting..."
                sleep 5
              done
              echo "OnePasswordItem CRD is now available!"
      restartPolicy: Never
  backoffLimit: 4